adding documentation for gist 12
semanticarts/gist-doc pull request #5
Opened 2023-08-07 08:06 UTC by pwin

2023-10-02 19:21 UTC, sa-bpelakh reviewed
This can't be reviewed like a normal PR, given that's a live HTML document (and a epub, for which I need to find a reader). but I have a couple of questions:
1. Why are you removing the gist 11-0 docs, as opposed to just archiving it? Sometimes people might need to reference old documentation, if they have not yet upgraded.
2. Why are we putting d3 and webowl under our source control, as opposed to loading them from their normal locations? I am not even sure if we are allowed to redistribute them in this fashion.

2023-10-03 14:42 UTC, pwin commented
so should we turn this into a website ?

On Mon, 2 Oct 2023 at 20:21, Boris Pelakh ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> This can't be reviewed like a normal PR, given that's a live HTML document
> (and a epub, for which I need to find a reader). but I have a couple of
> questions:
>
>    1. Why are you removing the gist 11-0 docs, as opposed to just
>    archiving it? Sometimes people might need to reference old documentation,
>    if they have not yet upgraded.
>    2. Why are we putting d3 and webowl under our source control, as
>    opposed to loading them from their normal locations? I am not even sure if
>    we are allowed to redistribute them in this fashion.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/semanticarts/gist-doc/pull/5#pullrequestreview-1653353089>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIFYTECNSDX6WNMAWEDVWTX5MH4VAVCNFSM6AAAAAA3GTIYGWVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNJTGM2TGMBYHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-03 15:13 UTC, Jamie-SA commented
https://gist-doc.semanticarts.com/

Maybe it should get added to the README.

2023-10-04 14:19 UTC, rjyounes commented
> Why are you removing the gist 11-0 docs, as opposed to just archiving it? Sometimes people might need to reference old documentation, if they have not yet upgraded.

I agree 100%. I had all along envisioned that we would keep all prior documentation in versioned folders.

2023-10-04 14:35 UTC, rjyounes requested changes

2023-10-04 14:35 UTC, rjyounes commented on README.md
> +Current version of gist: 12.0.0
Are we going to refresh this only at major releases? And not have to update this line every time we publish a new version of gist? Then we should say 

Current major version of gist: 12

Or 

Current version of gist: 12.x.x ("Current version" not quite right here, I don't know how to refer to this).

2023-10-04 14:35 UTC, rjyounes commented on README.md
> +  * The organization of the eBook is based around the idea of themes of classes and predicates that deal with related concepts.
```suggestion
  * The eBook is organized around conceptual themes, such as addresses, magnitudes, and so on.
```

2023-10-04 14:35 UTC, rjyounes commented on README.md
> +  * epub format distribution of the "Zest of gist" eBook will work with any modern eBook reader including Calibre and Kindle reader
```suggestion
  * The epub distribution will work with any modern eBook reader, including Calibre and Kindle reader.
```

2023-10-04 14:35 UTC, rjyounes commented on README.md
> +* **gist eBook**
```suggestion
* **gist eBook: _The Zest of Gist_**
```
Not sure if this formatting works. I'm going for the title in italics inside the bold.

2023-10-04 14:35 UTC, rjyounes commented on README.md
> +Current version of gist: 12.0.0
I would also name the eBook in some way that doesn't make it out of date with patch or minor versions.

2023-10-04 14:35 UTC, rjyounes commented on gist-12.0/widoco-documentation/readme.md
> +About Widoco output
```suggestion
About Widoco Output
```

2023-10-04 14:35 UTC, rjyounes commented on gist-12.0/widoco-documentation/readme.md
> +===================
Why do we need documentation of widoco itself? We are not expecting anyone to create the widoco documentation. When they view the widoco documentation they will see immediately what it is and how it is structured.  If we really want, we can just link to existing widoco documentation, say here: https://github.com/dgarijo/Widoco. I recommend removing the entire section.

2023-10-04 14:37 UTC, rjyounes commented
> https://gist-doc.semanticarts.com/

This is a good initial version. I would like to see two things in the future:
* Standardize on gist-doc or gist-docs (singular vs plural). We are using each in various places - repo name, link, HTML title, etc. I don't have a preference but I like consistency.
* At some point add some CSS to the web page.

2024-03-13 22:23 UTC, rjyounes commented
Closing - superseded by PR #10.

2024-03-13 22:23 UTC, closed without merging